### ISSUE TITLE
Fonctionnalites admin

### ISSUE THREAD

**Issue by grangea** [DAC-2014-Equipe-3/sujet-2#10]
Pb cloture projet admin
Verifier supprimer projet admin

**Comment by grangea** [comment]
Ok pour la suppression des projets mais pb affichage message !
Pour suppression admin, toujours BUG !

**Comment by Jummartinezro** [comment]
Corrigé la suppression de projet et l'affichage de message

**Comment by Jummartinezro** [comment]
Suppression admin corrigé
