### ISSUE TITLE
Investir projet

### ISSUE THREAD

**Issue by grangea** [DAC-2014-Equipe-3/sujet-2#17]
Une fois l'investissement réussi, la page est bloquée (index.html). Aucun onglet n'est cliquable...

**Comment by Jummartinezro** [comment]
J'ai essayé et ça marche ...
Par contre, il faut corriger les images pour montrer les boutons et il y a une exception lorsqu'il n'y a pas de reward associé au projet

**Comment by grangea** [comment]
Cad?
