### ISSUE TITLE
Plusieurs investissements pour un m projet

### ISSUE THREAD

**Issue by grangea** [DAC-2014-Equipe-3/sujet-2#5]
Modifier cle primaire de member backs project
Comme on avait dit, pour permettre linvestissement dun m gars sur un projet

**Comment by elomedah** [comment]
Humm, j'ai pas compris ??

2015-01-15 17:06 GMT+02:00 grangea notifications@github.com:

> Assigned #5 https://github.com/DAC-2014-Equipe-3/sujet-2/issues/5 to
> @elomedah https://github.com/elomedah.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DAC-2014-Equipe-3/sujet-2/issues/5#event-219454012.

## 

Kodjo Mawuélom EDAH
Tel: (0033) 0752941408
Élève ingénieur, ENSIMAG, INP-Grenoble &
Ecole Nationale Supérieure d'Informatique et
d'Analyse des  Systèmes (Maroc)
Skype: Elom.Edah1
